"""
Read 성경/창세기_*.txt and emit bible-genesis.js with const GENESIS map.
Run: python build_genesis.py
"""
import os, re, json

ROOT = os.path.dirname(os.path.abspath(__file__))
SRC_DIR = os.path.join(ROOT, "성경")
OUT = os.path.join(ROOT, "bible-genesis.js")
CHAPTERS = 50

def parse_chapter(path):
    verses = {}
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            m = re.match(r"^(\d+)\s+(.+)$", line)
            if m:
                verses[int(m.group(1))] = m.group(2)
    return verses

def main():
    chapters = {}
    for ch in range(1, CHAPTERS + 1):
        p = os.path.join(SRC_DIR, f"창세기_{ch}장.txt")
        chapters[ch] = parse_chapter(p)
    parts = []
    for ch in sorted(chapters):
        items = []
        for v in sorted(chapters[ch]):
            items.append(f'"{v}":{json.dumps(chapters[ch][v], ensure_ascii=False)}')
        parts.append(f'  "{ch}":{{{",".join(items)}}}')
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// 개역개정 창세기 (전 50장) — auto-generated by build_genesis.py\n")
        f.write("const GENESIS = {\n")
        f.write(",\n".join(parts))
        f.write("\n};\n")
    total = sum(len(v) for v in chapters.values())
    print(f"wrote {OUT}: {total} verses across {len(chapters)} chapters")

if __name__ == "__main__":
    main()
