"""
build_bible.py — generate bible-all.js from 성경/*.txt files.

Reads every 성경/{korean_name}_{N}{장|편}.txt that exists for the books in BOOKS,
and writes a single bible-all.js containing:
  const BIBLE_DATA = { "<key>": { 1: {1: "...", ...}, ... }, ... };
  const BIBLE_MANIFEST = [ {key, name, chapterCount, unit}, ... ];

Verse text is read from disk and written to disk only — it never goes to stdout.
The script prints just a compact JSON summary so the calling agent stays
token-efficient. Use --quiet to suppress all output except the summary.

Usage:
  python build_bible.py
  python build_bible.py --only genesis,exodus
  python build_bible.py --quiet
"""
import argparse, json, os, re, sys

ROOT = os.path.dirname(os.path.abspath(__file__))
SRC_DIR = os.path.join(ROOT, "성경")
OUT = os.path.join(ROOT, "bible-all.js")

# (key, korean_name, chapter_count) — order is the canonical 66-book order
BOOKS = [
    ("genesis", "창세기", 50), ("exodus", "출애굽기", 40), ("leviticus", "레위기", 27),
    ("numbers", "민수기", 36), ("deuteronomy", "신명기", 34), ("joshua", "여호수아", 24),
    ("judges", "사사기", 21), ("ruth", "룻기", 4),
    ("1samuel", "사무엘상", 31), ("2samuel", "사무엘하", 24),
    ("1kings", "열왕기상", 22), ("2kings", "열왕기하", 25),
    ("1chronicles", "역대상", 29), ("2chronicles", "역대하", 36),
    ("ezra", "에스라", 10), ("nehemiah", "느헤미야", 13), ("esther", "에스더", 10),
    ("job", "욥기", 42), ("psalms", "시편", 150), ("proverbs", "잠언", 31),
    ("ecclesiastes", "전도서", 12), ("songofsongs", "아가", 8),
    ("isaiah", "이사야", 66), ("jeremiah", "예레미야", 52), ("lamentations", "예레미야애가", 5),
    ("ezekiel", "에스겔", 48), ("daniel", "다니엘", 12),
    ("hosea", "호세아", 14), ("joel", "요엘", 3), ("amos", "아모스", 9),
    ("obadiah", "오바댜", 1), ("jonah", "요나", 4), ("micah", "미가", 7),
    ("nahum", "나훔", 3), ("habakkuk", "하박국", 3), ("zephaniah", "스바냐", 3),
    ("haggai", "학개", 2), ("zechariah", "스가랴", 14), ("malachi", "말라기", 4),
    ("matthew", "마태복음", 28), ("mark", "마가복음", 16), ("luke", "누가복음", 24),
    ("john", "요한복음", 21), ("acts", "사도행전", 28), ("romans", "로마서", 16),
    ("1corinthians", "고린도전서", 16), ("2corinthians", "고린도후서", 13),
    ("galatians", "갈라디아서", 6), ("ephesians", "에베소서", 6), ("philippians", "빌립보서", 4),
    ("colossians", "골로새서", 4),
    ("1thessalonians", "데살로니가전서", 5), ("2thessalonians", "데살로니가후서", 3),
    ("1timothy", "디모데전서", 6), ("2timothy", "디모데후서", 4),
    ("titus", "디도서", 3), ("philemon", "빌레몬서", 1),
    ("hebrews", "히브리서", 13), ("james", "야고보서", 5),
    ("1peter", "베드로전서", 5), ("2peter", "베드로후서", 3),
    ("1john", "요한일서", 5), ("2john", "요한이서", 1), ("3john", "요한삼서", 1),
    ("jude", "유다서", 1), ("revelation", "요한계시록", 22),
]

VERSE_RE = re.compile(r"^(\d+)\s+(.+)$")


def parse_chapter(path):
    verses = {}
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n").strip()
            if not line or line.startswith("["):
                continue
            m = VERSE_RE.match(line)
            if m:
                verses[int(m.group(1))] = m.group(2)
    return verses


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", default="", help="comma-separated keys to include (default: all)")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    only = set(s.strip() for s in args.only.split(",") if s.strip())
    book_data = {}
    manifest = []
    missing_chapters = []
    total_verses = 0

    for key, name, ch_count in BOOKS:
        if only and key not in only:
            continue
        unit = "편" if name == "시편" else "장"
        chapters = {}
        for ch in range(1, ch_count + 1):
            path = os.path.join(SRC_DIR, f"{name}_{ch}{unit}.txt")
            if not os.path.exists(path):
                missing_chapters.append(f"{key}/{ch}")
                continue
            verses = parse_chapter(path)
            if not verses:
                missing_chapters.append(f"{key}/{ch}")
                continue
            chapters[ch] = verses
            total_verses += len(verses)
        if not chapters:
            continue
        book_data[key] = chapters
        manifest.append({"key": key, "name": name, "chapterCount": ch_count, "unit": unit})

    lines = [
        "// auto-generated by build_bible.py — DO NOT EDIT BY HAND",
        "// Regenerate with: python build_bible.py",
        "",
        "const BIBLE_DATA = {",
    ]
    for key in [m["key"] for m in manifest]:
        lines.append(f'  "{key}": {{')
        ch_lines = []
        for ch in sorted(book_data[key]):
            verses = book_data[key][ch]
            inner = ",".join(
                f'"{v}":{json.dumps(verses[v], ensure_ascii=False)}' for v in sorted(verses)
            )
            ch_lines.append(f'    "{ch}":{{{inner}}}')
        lines.append(",\n".join(ch_lines))
        lines.append("  },")
    lines.append("};")
    lines.append("")
    lines.append("const BIBLE_MANIFEST = " + json.dumps(manifest, ensure_ascii=False, indent=2) + ";")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    summary = {
        "ok": True,
        "out": os.path.relpath(OUT, ROOT),
        "books": len(book_data),
        "chapters": sum(len(v) for v in book_data.values()),
        "verses": total_verses,
        "size_bytes": os.path.getsize(OUT),
        "missing_chapters": missing_chapters,
    }
    print(json.dumps(summary, ensure_ascii=False))


if __name__ == "__main__":
    main()
